### ISSUE TITLE
File Error: 1039

### ISSUE THREAD

**Issue by johnnyxmas** [sckunkle/mbotmake#2]
Vague error on Makerbot 5th Gen on FW v2.6.1.724. Prints initial test line at the bottom of the plate and then halts. 

[logs.zip](https://github.com/sckunkle/mbotmake/files/4489281/logs.zip)

[covid-mask.gcode.zip](https://github.com/sckunkle/mbotmake/files/4489285/covid-mask.gcode.zip)

**Comment by powpingdone** [comment]
Looking at your GCODE it seems to me that you don't have the origin centered. Whats your prusaslicer config say on your bed dimensions?

**Comment by johnnyxmas** [comment]
252 x 198, which should be fine. Origin is set to 0,0.

Thank You,
Johnny Xmas
Security Advocate || CISSP - GIAC - GPEN
PGP / Keybase: https://keybase.io/j0hnnyxm4s <https://keybase.io/j0hnnyxm4s>
Twitter & Wickr: @J0hnnyXm4s || Insecure: (410)H4X-0R3D

**Comment by powpingdone** [comment]
Your origin should be 127,100. Try slicing with that origin.

**Comment by johnnyxmas** [comment]
Yep; that worked. Sorry to make an issue out of it.

Thank You,
Johnny Xmas
Security Advocate || CISSP - GIAC - GPEN
PGP / Keybase: https://keybase.io/j0hnnyxm4s <https://keybase.io/j0hnnyxm4s>
Twitter & Wickr: @J0hnnyXm4s || Insecure: (410)H4X-0R3D

**Comment by powpingdone** [comment]
Alright then. Closing.
