### ISSUE TITLE
How do I create a makerbot file from the gcodes in the examples?

### ISSUE THREAD

**Issue by Conzar** [sckunkle/mbotmake#3]
I am using Python 3.8 on Ubuntu 20.04 and issued the following command:

```bash
python3.8 mbotmake testcases/cura\ gcode/CFFFP_xyzCalibration_cube.gcode 
```

Which generates the CFFFP_xyzCalibration_cube.makerbot file.  When I load this onto the printer, it has no information other than the completion time.  Zero for all the other information like temperature, etc.  I haven't run the file due to the missing information.

Should the information look similar to the cube in the simplify3d directory?  If so, what am I doing wrong?

**Comment by powpingdone** [comment]
It has been a very long time since i've used this in a actual environment, but it doesnt seem to be generating the temp into the  meta.json . Open the .makerbot with a archive opener and see if the meta.json creates a temperature. 

By default it will not have a picture.

**Comment by powpingdone** [comment]
Oh, my bad. I checked the examples and they didn't have M104 gcodes. Whoops. Don't use them.
