### ISSUE TITLE
Does not heat extruder temperature

### ISSUE THREAD

**Issue by RoCkHeLuCk** [sckunkle/mbotmake#6]
Good morning, first of all, I would like to thank you and congratulate you on the development of this tool.
I was able to use the marlin flavored "cura" and convert it using this tool to print on the updated Makerbot Replicator +. It works very well after editing the json manually, in the first tests I did I saw that the extruder was not heating, so I edit the json manually and set the correct temperature, it always comes with the value 0.
I would like to know if I am doing something wrong in "cura" or there really is no implementation in the code for this?
I did some checks, both the M104 S200 and M105 and M109 S200 codes are in the gcode.
I'm also catching it at the time of the first layer, but I believe it's just a matter of adjusting the "cure".
Thank you very much for the help.

**Comment by powpingdone** [comment]
This code was only tested on the makerbot replicator generation 5 printer. You might want to check out how the `.makerbot` generated by the slicer is constructed in comparison to what this python script does.

**Comment by RoCkHeLuCk** [comment]
That's what I did, I checked that in "meta.json" there are variables "toolhead_0_temperature" and "extruder_temperatures" which are always set to "0", then I edit them manually to the correct value before sending them to the printer. So asking you, am I doing something wrong in the "cura" for these values ​​not to be updated or is there a lack of implementation in the code for this?

**Comment by powpingdone** [comment]
Most likely not implemented in my code.

**Comment by RoCkHeLuCk** [comment]
I took the liberty of checking your code. I believe it is missing near line 170, where it reads "M104" and is adding the reference "set_toolhead_temperature", but the variable is "toolhead_0_temperature", my doubt is whether this difference is in relation to other versions of Makerbot. Do you have or remember this?

**Comment by powpingdone** [comment]
Unfortunately, I don't know if there is a difference between different versions of makerbot packaging. 

Do the M104 in your gcode specify the toolhead to heat?

**Comment by RoCkHeLuCk** [comment]
The printer I'm using "Makerbot Replicador +" doesn't have a heated table or a second extruder. Lines 15 to 29 of your code assemble the structure with these variables, but do not fill them with the value of "M104", etc...
So much so that when I convert a ".gcode" to a ".makerbot" with its algorithm, all these "meta.json" variables come with 0, minus duration_s, total_commands. Manually I change the value 0 to the correct temperature and put it to print, then it works, on the contrary it doesn't heat up and stops.
In the print.jsontoolpath file there is the variable "set_toolhead_temperature" which is filled with the value of "M104", but in my case it seems that it does not heat the hotend.
I want to change the electronics and install Marlin with a really good gcode. :)
